function disp_colors = choose_channel_ui(defaults)



colors = [1 2 3 4];
d = dialog('Position',[300 300 250 170],'Name','Select One');

txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 130 210 20],...
    'String','Select a channel to DROP');

bg = uibuttongroup('Parent',d,...
    'Visible','off','Position',[0.25 .35 0.5 0.4], ...
    'SelectionChangedFcn',{@bg_value, colors});

r1 = uicontrol(bg,'Style',...
    'radiobutton',...
    'Units', 'normalized',...
    'Position', [0.2 0.8 .7 .2],...
    'String','Channel 1',...
    'HandleVisibility','off');

r2 = uicontrol(bg,'Style',...
    'radiobutton',...
    'Units', 'normalized',...
    'Position', [0.2 0.55 .7 .2],...
    'String','Channel 2',...
    'HandleVisibility','off');

r3 = uicontrol(bg,'Style',...
    'radiobutton',...
    'Units', 'normalized',...
    'Position', [0.2 0.3 .7 .2],...
    'String','Channel 3',...
    'HandleVisibility','off');

r4 = uicontrol(bg,'Style',...
    'radiobutton',...
    'Units', 'normalized',...
    'Position', [0.2 0.05 .7 .2],...
    'String','Channel 4',...
    'HandleVisibility','off');

btn = uicontrol('Parent',d,...
    'Position',[89 20 70 25],...
    'String','Close',...
    'Callback','delete(gcf)');

bg.Visible = 'on';



% Wait for d to close before running to completion

% uiwait(d);

    function disp_colors = bg_value(source, event, colors)
        disp([event.NewValue.String ' dropped']);
        channel = str2double(event.NewValue.String(length(event.NewValue.String)));
       
        disp_colors = colors;
        
        disp_colors(ismember(disp_colors, channel)) = [];
        
        %disp(disp_colors)
        
    end


end